Repository MattiaCinelli/AlgoRL, pull requests merged in 2022-04, with the labels that each got.

#15 added GBA and general formatting
  algorl/src/DP.py
  algorl/src/MC.py
  algorl/src/TD.py
  algorl/src/bandit.py
  algorl/src/grid_environment.py
  main_dc.py
  main_mab.py
  main_mc.py
Labels: documentation, enhancement

#16 Refactoring and bug fixing for TD.py
  algorl/src/MC.py
  algorl/src/TD.py
  algorl/src/bandit.py
  algorl/src/grid_environment.py
  main_mc.py
  run_td.py
Labels: documentation, enhancement

#17 Adding n-step algorithms
  algorl/src/MC.py
  algorl/src/Nstep.py
  algorl/src/TD.py
  algorl/src/bandit.py
  algorl/src/grid_environment.py
  algorl/src/tool_box.py
  main_dc.py
  main_mab.py
  main_mc.py
  run_td.py
Labels: documentation, enhancement

#20 Aglw/gridworld examples
  .gitignore
  algorl/src/DP.py
  algorl/src/grid_environment.py
Labels: enhancement

#19 Mc/plotnine draft
  algorl/src/bandit.py
  main_mab.py
Labels: good first issue

#18 Adding a first draft of testing
  tests/README.md
  tests/conftest.py
  tests/test_MAB.py
  tests/test_tool_box.py
Labels: good first issue

#21 Double Q learning algorithm
  README.md
  algorl/src/TD.py
  run_td.py
Labels: enhancement
